apply plugin: 'java'
apply plugin: 'maven-publish'

group = 'de.schoko.json'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    sourceCompatibility = "21"
    targetCompatibility = "21"

    withSourcesJar()
}

tasks.named('test', Test) {
    useJUnitPlatform()

    maxHeapSize = '1G'

    testLogging {
        events "passed"
    }
}

wrapper {
    gradleVersion = "9.3.0"
    distributionType = Wrapper.DistributionType.ALL
}